chore: update deps and publishing

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,13 +9,13 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        node-version: [20.x, 22.x]
+        node-version: [20.x, 22.x, 24.x]
 
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
 
       - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v4
+        uses: actions/setup-node@v6
         with:
           node-version: ${{ matrix.node-version }}
 
@@ -27,3 +27,13 @@ jobs:
 
       - name: Build the project
         run: yarn build
+        env:
+          CI: true
+
+      - name: List, audit, fix outdated dependencies and build again
+        run: |
+          yarn list --outdated
+          yarn audit || true  # ignore failures
+          yarn audit fix || true
+          yarn list --outdated
+          yarn build
